### ISSUE TITLE
Create an endpoint for deleting a Tweet.

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-rails-api#13]
### Tasks

- [x] Create the endpoint.
- [x] Write new tests.
- [x] Fix affected tests.
- [x] Modify API documentation.
