### ISSUE TITLE
Create an endpoint for viewing the details of a Tweet.

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-rails-api#14]
### Tasks

- [x] Write specs for the new endpoint.
- [x] Create a new endpoint.
- [x] Modify endpoint for getting the list of all Tweets.
- [x] Fix affected RSpec tests.
- [x] Update REST API documentation.
- [x] Modify `db/seeds.rb`.
