### ISSUE TITLE
Create a GraphQL endpoint.

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-rails-api#36]
### Tasks

- [x] Add `graphql` as a dependency.
- [x] Add `graphiql-rails` as a dependency.
- [x] Setup endpoints for GraphQL and GraphiQL.
- [x] Port all existing endpoints to GraphQL whenever possible.
- [x] Modify the necessary Markdown docs.
- [x] Ensure that the Dockerized instance is still okay.

### Related issues from other repositories

- rmosolgo/graphiql-rails#13

[1]: https://github.com/wayfair/dociql
